version: '3.8'
services:
  app:
    build:
      context: .
      target: execution
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_MAIL_HOST=maildev
    ports:
      - "8080:8080"
  db:
    image: 'postgres:latest'
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"